import { Client, SSEP, Appointment, PostVisitNote } from '@/types';

export const TODAY = '2026-06-07';

export const sseps: SSEP[] = [
  {
    id: 'ssep-1',
    name: 'Jordan M.',
    role: 'Primary Experience Professional',
    skills: ['non-verbal support', 'child-friendly pacing', 'scissor-only comfort', 'visual schedule use'],
    availability: 'Busy',
    bio: 'Jordan specializes in working with younger clients who need extra time and quiet environments. Known for patience and creativity with engagement tools.',
    assignedAppointments: ['appt-1', 'appt-3'],
  },
  {
    id: 'ssep-2',
    name: 'Alex R.',
    role: 'Sensory Experience Professional',
    skills: ['low-sound service', 'slow transition support', 'teen/adult sensory support', 'high-anxiety experience'],
    availability: 'Available',
    bio: 'Alex brings calm energy to every appointment. Especially skilled with older clients and those who need very low stimulation environments.',
    assignedAppointments: ['appt-2'],
  },
  {
    id: 'ssep-3',
    name: 'Taylor B.',
    role: 'Comfort & Calm Specialist',
    skills: ['high-anxiety client experience', 'deep pressure calming', 'child-friendly pacing', 'caregiver collaboration'],
    availability: 'Busy',
    bio: 'Taylor has extensive experience with high-support clients and works closely with caregivers to co-create each visit experience.',
    assignedAppointments: ['appt-4', 'appt-5'],
  },
  {
    id: 'ssep-4',
    name: 'Sam K.',
    role: 'Engagement & Regulation Specialist',
    skills: ['non-verbal communication', 'train/media engagement', 'sensory regulation', 'slow transition support'],
    availability: 'Available',
    bio: 'Sam uses interest-based engagement strategies and has a gift for building trust with clients who struggle with new environments.',
    assignedAppointments: ['appt-6'],
  },
];

export const clients: Client[] = [
  {
    id: 'client-1',
    firstName: 'Aiden',
    lastName: 'Thompson',
    age: 8,
    dateOfBirth: '2018-03-14',
    pronouns: 'He/Him',
    comfortRisk: 'Moderate',
    lastVisitDate: '2026-05-10',
    tags: ['train enthusiast', 'returning client', 'visual supports'],
    isNewClient: false,
    caregiver: {
      name: 'Sarah Thompson',
      relationship: 'Mother',
      phone: '555-201-4455',
      email: 'sarah.thompson@email.com',
      notes: 'Very engaged caregiver. Brings train book each visit.',
    },
    ecp: {
      communicationStyle: 'Verbal with visual supports. Responds well to picture schedules and step-by-step explanations.',
      primaryLanguage: 'English',
      verbalAbility: 'Fully verbal, may become non-verbal under high stress',
      sensoryAvoidances: ['loud clippers', 'wet hair on neck', 'unexpected touch'],
      sensoryPreferences: ['light pressure on shoulders', 'warm water rinse', 'soft towel'],
      calmingStrategies: ['train videos on tablet', 'counting steps aloud', 'fidget spinner'],
      transitionSupport: 'Needs 2-minute verbal warning before any chair movement. Use "almost done" cue.',
      motivators: ['trains', 'dinosaurs', 'sticker reward after visit'],
      triggers: ['sudden loud noises', 'clippers without warning', 'mirror surprise'],
      groomingHistory: 'Has been coming for 14 months. First 3 visits were difficult — now settles within 5 minutes.',
      visitGoals: 'Maintain comfort level. Introduce hair wash this cycle.',
      staffNotes: 'Train book is the golden ticket. Keep clipper guard on until he gives thumbs up.',
    },
    res: {
      lighting: 'Dim overhead, warm side lamp. Avoid fluorescent direct.',
      soundLevel: 'Low — no music, or very soft instrumental only',
      chairType: 'Booster seat, standard chair reclined slightly',
      calmingTools: ['train video tablet', 'fidget spinner', 'weighted lap pad'],
      visuals: 'Picture schedule on counter. Show each step before doing.',
      servicePacing: 'Slow and narrated. Pause between each step.',
      transitionTimeEstimate: '5 minutes pre-chair, 2 minutes between each service step',
      doNotUseTriggers: ['electric clippers near ears without prior exposure', 'hood over face', 'surprise spray bottle'],
      ssepRecommendation: 'Jordan M. (primary relationship built)',
    },
  },
  {
    id: 'client-2',
    firstName: 'Maya',
    lastName: 'Rodriguez',
    age: 6,
    dateOfBirth: '2020-01-22',
    pronouns: 'She/Her',
    comfortRisk: 'High',
    lastVisitDate: undefined,
    tags: ['new client', 'visual learner', 'high support'],
    isNewClient: true,
    caregiver: {
      name: 'Carmen Rodriguez',
      relationship: 'Mother',
      phone: '555-334-8821',
      email: 'carmen.r@email.com',
      notes: 'Mother is very anxious about the visit. Reassure her first so she can stay calm for Maya.',
    },
    ecp: {
      communicationStyle: 'Limited verbal. Uses picture exchange cards at home. Responds to gestures and modeling.',
      primaryLanguage: 'Spanish/English bilingual',
      verbalAbility: 'Minimal verbal output — 5-10 words. Communicates primarily through pointing and body language.',
      sensoryAvoidances: ['buzzing sounds', 'neck cape touch', 'hair dryer heat', 'multiple people talking at once'],
      sensoryPreferences: ['bubbles (visual)', 'soft brush on hands', 'rainbow spinner toy'],
      calmingStrategies: ['bubble machine', 'caregiver proximity', 'soft singing by caregiver'],
      transitionSupport: 'Caregiver leads transition. Do not initiate physical guidance without consent signal.',
      motivators: ['bubbles', 'rainbow colors', 'stickers', 'caregiver praise'],
      triggers: ['any buzzing near head', 'raised voices', 'cold water', 'being left alone'],
      groomingHistory: 'First salon visit ever. Previous experiences at home only, with significant distress.',
      visitGoals: 'Positive first impression. Even partial service is a win.',
      staffNotes: 'Go VERY slow. If she signs "stop" or covers ears, pause everything immediately. Mother speaks Spanish — have her translate as needed.',
    },
    res: {
      lighting: 'Soft warm light only. Dim to minimum.',
      soundLevel: 'Silent or near-silent. No music. No adjacent chatter audible.',
      chairType: 'Caregiver lap first — transition to chair only if she initiates',
      calmingTools: ['bubble machine', 'rainbow spinner', 'caregiver proximity'],
      visuals: 'Bilingual visual schedule (Spanish/English). Minimal text, max icons.',
      servicePacing: 'Extremely slow. One action at a time. Full stops between steps.',
      transitionTimeEstimate: '10 minutes decompression on arrival. 15-minute total service max for first visit.',
      doNotUseTriggers: ['clippers of any kind this visit', 'hairdryer', 'loud spray bottles', 'strangers approaching'],
      ssepRecommendation: 'Taylor B. (high-anxiety experience specialist)',
    },
  },
  {
    id: 'client-3',
    firstName: 'Jordan',
    lastName: 'Lee',
    age: 12,
    dateOfBirth: '2014-08-05',
    pronouns: 'They/Them',
    comfortRisk: 'Low',
    lastVisitDate: '2026-05-28',
    tags: ['music-focused', 'returning client', 'independent'],
    isNewClient: false,
    caregiver: {
      name: 'Wei Lee',
      relationship: 'Parent',
      phone: '555-112-6677',
      email: 'wei.lee@email.com',
      notes: 'Prefers to wait in lobby. Jordan is comfortable independently.',
    },
    ecp: {
      communicationStyle: 'Fully verbal. Direct communication preferred. Does not like small talk — prefers task-focused conversation.',
      primaryLanguage: 'English',
      verbalAbility: 'Fully verbal and articulate. Will clearly state preferences.',
      sensoryAvoidances: ['scented products', 'tight cape', 'overhead sprayer'],
      sensoryPreferences: ['music through personal earbuds', 'consistent temperature water', 'gentle scalp pressure'],
      calmingStrategies: ['own music playlist', 'minimal conversation', 'knowing exactly what will happen'],
      transitionSupport: 'Verbal schedule at start is enough. No additional transition support needed.',
      motivators: ['music', 'efficiency', 'respecting their autonomy'],
      triggers: ['scented shampoo', 'unexpected service additions', 'being talked over'],
      groomingHistory: 'Regular client for 2 years. Very cooperative once routine is established.',
      visitGoals: 'Consistent, efficient service with sensory accommodations honored.',
      staffNotes: 'Let them put earbuds in before starting. Ask before switching any product. Very self-aware — trust their input.',
    },
    res: {
      lighting: 'Normal overhead fine — they are not light-sensitive',
      soundLevel: 'Personal earbuds preferred. Ambient sound okay.',
      chairType: 'Standard chair, upright position',
      calmingTools: ['personal music device', 'unscented products only'],
      visuals: 'Verbal rundown at start. No visual schedule needed.',
      servicePacing: 'Normal to brisk — they prefer efficient service',
      transitionTimeEstimate: '1 minute max. Very adaptable.',
      doNotUseTriggers: ['scented shampoo/conditioner', 'overhead water sprayer', 'adding services without asking'],
      ssepRecommendation: 'Alex R. (low-stimulation, respects autonomy)',
    },
  },
  {
    id: 'client-4',
    firstName: 'Caleb',
    lastName: 'Washington',
    age: 5,
    dateOfBirth: '2021-11-30',
    pronouns: 'He/Him',
    comfortRisk: 'High',
    lastVisitDate: undefined,
    tags: ['new client', 'high support', 'heavy prep needed', 'pre-visit call required'],
    isNewClient: true,
    caregiver: {
      name: 'Marcus Washington',
      relationship: 'Father',
      phone: '555-445-9930',
      email: 'marcus.w@email.com',
      notes: 'Father has done extensive prep with social stories. Bring up the social story book during visit.',
    },
    ecp: {
      communicationStyle: 'Social stories and visual schedules. Uses AAC device at school. Echolalic at times.',
      primaryLanguage: 'English',
      verbalAbility: 'Limited functional speech. Uses AAC device. May echo phrases from videos.',
      sensoryAvoidances: ['water near face', 'clippers near any body part', 'strangers in personal space', 'multiple simultaneous sounds'],
      sensoryPreferences: ['deep pressure input', 'heavy blanket', 'low vibration/hum'],
      calmingStrategies: ['deep pressure vest', 'social story about haircut', 'father narrating steps'],
      transitionSupport: 'Father must be present throughout. Use social story book to preview each step.',
      motivators: ['construction trucks', 'YouTube Kids vehicle videos', 'high-five celebration'],
      triggers: ['water near face', 'clippers sound', 'sudden movement in mirror', 'losing line of sight to father'],
      groomingHistory: 'No successful salon experience. Previous attempts ended in full distress response.',
      visitGoals: 'Sit in chair with father present. Any tool introduction is bonus.',
      staffNotes: 'This is a trust-building visit only. Do not rush. Success = Caleb feels safe. Father has a social story book — ask him to bring it in.',
    },
    res: {
      lighting: 'Dimmed to minimum. Cover or angle any mirrors.',
      soundLevel: 'Silent. All nearby staff briefed. No clippers on in room.',
      chairType: 'Father lap only for this visit. Chair only if Caleb initiates.',
      calmingTools: ['deep pressure vest (father brings)', 'social story book', 'vehicle video tablet', 'heavy lap blanket'],
      visuals: 'Social story book — each page = one step. Do not advance until Caleb turns the page.',
      servicePacing: 'Extremely slow. Trust-building visit only.',
      transitionTimeEstimate: '15 minutes decompression. No time limit on service.',
      doNotUseTriggers: ['any clippers — even showing them', 'spray bottle near head', 'leaning over him from behind', 'dryer'],
      ssepRecommendation: 'Taylor B. with Sam K. as secondary (high-anxiety + engagement support)',
    },
  },
  {
    id: 'client-5',
    firstName: 'Priya',
    lastName: 'Patel',
    age: 9,
    dateOfBirth: '2017-06-19',
    pronouns: 'She/Her',
    comfortRisk: 'Low',
    lastVisitDate: '2026-05-20',
    tags: ['returning client', 'cooperative', 'peer model candidate'],
    isNewClient: false,
    caregiver: {
      name: 'Anita Patel',
      relationship: 'Mother',
      phone: '555-678-1234',
      email: 'anita.patel@email.com',
      notes: 'Mother is interested in peer modeling program. Follow up.',
    },
    ecp: {
      communicationStyle: 'Fully verbal, enthusiastic communicator. Loves to chat with SSEP during service.',
      primaryLanguage: 'English',
      verbalAbility: 'Fully verbal. Highly expressive.',
      sensoryAvoidances: ['cold water rinse', 'strong scented products'],
      sensoryPreferences: ['warm water', 'scalp massage', 'chatting about her day'],
      calmingStrategies: ['conversation', 'warm towel wrap', 'choosing her own music'],
      transitionSupport: 'No additional support needed. Very adaptable.',
      motivators: ['music', 'conversation', 'compliments', 'mirror check at the end'],
      triggers: ['cold water surprise', 'heavy cologne/perfume on stylist'],
      groomingHistory: 'Regular client for 3 years. No significant challenges.',
      visitGoals: 'Consistent positive experience. Mother exploring peer model program.',
      staffNotes: 'Priya is a great ambassador client. She may be able to participate in peer modeling for newer clients in the future.',
    },
    res: {
      lighting: 'Normal — no special accommodation',
      soundLevel: 'Light music okay. Chatty environment is fine.',
      chairType: 'Standard chair — any position',
      calmingTools: ['warm towel', 'music of her choice'],
      visuals: 'Not needed',
      servicePacing: 'Normal',
      transitionTimeEstimate: 'Minimal — very adaptable',
      doNotUseTriggers: ['cold water rinse without warning', 'heavy fragrance products'],
      ssepRecommendation: 'Any SSEP — she is adaptable. Jordan M. preferred for continuity.',
    },
  },
];

export const appointments: Appointment[] = [
  {
    id: 'appt-1',
    clientId: 'client-1',
    ssepId: 'ssep-1',
    date: TODAY,
    time: '9:00 AM',
    status: 'Completed',
    service: 'Haircut + Comfort Assessment',
    durationMinutes: 45,
    acc: {
      appointmentId: 'appt-1',
      timestamp: `${TODAY}T09:05:00`,
      moodRating: 4,
      changesSinceLastVisit: 'No major changes. Mom says he had a great week.',
      caregiverNotesToday: 'Brought new train book. Ready to try hair wash today.',
      sensoryCondition: 'Good',
      chairReadiness: 'Yes',
      recommendedDelayMinutes: 0,
      resUpdated: false,
    },
  },
  {
    id: 'appt-2',
    clientId: 'client-3',
    ssepId: 'ssep-2',
    date: TODAY,
    time: '10:00 AM',
    status: 'Arrived',
    service: 'Haircut',
    durationMinutes: 30,
    acc: {
      appointmentId: 'appt-2',
      timestamp: `${TODAY}T10:03:00`,
      moodRating: 3,
      changesSinceLastVisit: 'Tired from school event yesterday.',
      caregiverNotesToday: 'Parent waiting in lobby as usual.',
      sensoryCondition: 'Fair',
      chairReadiness: 'Yes',
      recommendedDelayMinutes: 0,
      resUpdated: false,
    },
  },
  {
    id: 'appt-3',
    clientId: 'client-5',
    ssepId: 'ssep-1',
    date: TODAY,
    time: '11:00 AM',
    status: 'In Progress',
    service: 'Haircut + Scalp Treatment',
    durationMinutes: 40,
    acc: {
      appointmentId: 'appt-3',
      timestamp: `${TODAY}T11:02:00`,
      moodRating: 5,
      changesSinceLastVisit: 'None. Very excited today.',
      caregiverNotesToday: 'Mom asked about peer modeling program timing.',
      sensoryCondition: 'Good',
      chairReadiness: 'Yes',
      recommendedDelayMinutes: 0,
      resUpdated: false,
    },
  },
  {
    id: 'appt-4',
    clientId: 'client-2',
    ssepId: 'ssep-3',
    date: TODAY,
    time: '1:00 PM',
    status: 'Pending',
    service: 'First Visit — Trust Building',
    durationMinutes: 60,
  },
  {
    id: 'appt-5',
    clientId: 'client-4',
    ssepId: 'ssep-3',
    date: TODAY,
    time: '2:30 PM',
    status: 'Pending',
    service: 'First Visit — Trust Building',
    durationMinutes: 60,
  },
  {
    id: 'appt-6',
    clientId: 'client-1',
    ssepId: 'ssep-4',
    date: TODAY,
    time: '4:00 PM',
    status: 'Pending',
    service: 'Follow-up Check-In',
    durationMinutes: 20,
  },
];

export const postVisitNotes: PostVisitNote[] = [
  {
    id: 'note-1',
    appointmentId: 'appt-1',
    clientId: 'client-1',
    whatWorked: 'Train book engagement was excellent. Hair wash introduced successfully — first time ever. Counting steps aloud kept him regulated throughout.',
    whatDidntWork: 'Slight escalation when clipper guard slipped near ear. Recovered quickly with counting strategy.',
    triggersObserved: ['unexpected clipper sound near right ear'],
    calmingToolsUsed: ['train video tablet', 'counting steps aloud', 'fidget spinner'],
    transitionSuccessRating: 4,
    clientComfortRating: 4,
    recommendedChanges: 'Continue narrating every step. Introduce hairdryer on low next visit — he was curious about it today.',
    caregiverFeedback: 'Mom was thrilled about the hair wash. Said he talked about trains the whole ride home.',
    likelyToReturn: 'Yes',
    timestamp: `${TODAY}T09:52:00`,
  },
];

export function getClientById(id: string): Client | undefined {
  return clients.find(c => c.id === id);
}

export function getSSEPById(id: string): SSEP | undefined {
  return sseps.find(s => s.id === id);
}

export function getAppointmentById(id: string): Appointment | undefined {
  return appointments.find(a => a.id === id);
}

export function getTodayAppointments(): Appointment[] {
  return appointments.filter(a => a.date === TODAY);
}

export function getPostVisitNoteByAppointment(appointmentId: string): PostVisitNote | undefined {
  return postVisitNotes.find(n => n.appointmentId === appointmentId);
}
